-- -------------------------------------------------------------
--
-- Module: filterSerialPipeline
-- Generated by MATLAB(R) 9.2 and the Filter Design HDL Coder 3.1.1.
-- Generated on: 2019-06-06 18:38:03
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- FIRAdderStyle: tree
-- TargetDirectory: /home/xmont/Desktop/KH
-- AddPipelineRegisters: on
-- Name: filterSerialPipeline
-- TestBenchStimulus: impulse step ramp chirp noise 
-- GenerateHDLTestBench: off

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 5
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filterSerialPipeline IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real  -- double
         );

END filterSerialPipeline;


----------------------------------------------------------------
--Module Architecture: filterSerialPipeline
----------------------------------------------------------------
ARCHITECTURE rtl OF filterSerialPipeline IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT coeff1                         : real := 5.7512867830429748E-02; -- double
  CONSTANT coeff2                         : real := 2.5547006487104679E-01; -- double
  CONSTANT coeff3                         : real := 3.9044432921018679E-01; -- double
  CONSTANT coeff4                         : real := 2.5547006487104679E-01; -- double
  CONSTANT coeff5                         : real := 5.7512867830429748E-02; -- double

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 4) := (0.0,0.0,0.0,0.0, 0.0); -- double
  SIGNAL product5                         : real := 0.0; -- double
  SIGNAL product4                         : real := 0.0; -- double
  SIGNAL product3                         : real := 0.0; -- double
  SIGNAL product2                         : real := 0.0; -- double
  SIGNAL product1                         : real := 0.0; -- double
  SIGNAL sum_final                        : real := 0.0; -- double
  SIGNAL sum1_1                           : real := 0.0; -- double
  SIGNAL sumpipe1_1                       : real := 0.0; -- double
  SIGNAL sum1_2                           : real := 0.0; -- double
  SIGNAL sumpipe1_2                       : real := 0.0; -- double
  SIGNAL sumpipe1_3                       : real := 0.0; -- double
  SIGNAL sum2_1                           : real := 0.0; -- double
  SIGNAL sumpipe2_1                       : real := 0.0; -- double
  SIGNAL sumpipe2_2                       : real := 0.0; -- double
  SIGNAL sum3_1                           : real := 0.0; -- double
  SIGNAL sumpipe3_1                       : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 4) <= (OTHERS => 0.0000000000000000E+00);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= filter_in;
        delay_pipeline(1 TO 4) <= delay_pipeline(0 TO 3);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  product5 <= delay_pipeline(4) * coeff5;

  product4 <= delay_pipeline(3) * coeff4;

  product3 <= delay_pipeline(2) * coeff3;

  product2 <= delay_pipeline(1) * coeff2;

  product1 <= delay_pipeline(0) * coeff1;

  sum1_1 <= product5 + product4;

  sum1_2 <= product3 + product2;

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe1_1 <= 0.0000000000000000E+00;
      sumpipe1_2 <= 0.0000000000000000E+00;
      sumpipe1_3 <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe1_1 <= sum1_1;
        sumpipe1_2 <= sum1_2;
        sumpipe1_3 <= product1;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  sum2_1 <= sumpipe1_1 + sumpipe1_2;

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe2_1 <= 0.0000000000000000E+00;
      sumpipe2_2 <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe2_1 <= sum2_1;
        sumpipe2_2 <= sumpipe1_3;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  sum3_1 <= sumpipe2_1 + sumpipe2_2;

  temp_process3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      sumpipe3_1 <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        sumpipe3_1 <= sum3_1;
      END IF;
    END IF; 
  END PROCESS temp_process3;

  sum_final <= sumpipe3_1;


  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= sum_final;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
